#ifndef COMMON_H
#define COMMON_H

/*
 * include autogenerated config header
 */

#include "config.h"

/*
 * debug definitions
 */

#if !defined(_debug) && defined(DEBUG)
#	define _debug 1
#endif

/*
 * common headers
 */

#include <shim.h>

#endif
